### ISSUE TITLE
Could you help with this

### ISSUE THREAD

**Issue by MistFenix** [marcoavesani/openwrt_image_build_rm2100#2]
Could you please help generate or learn how can I create with these options:
dnsmasq-full + nftables + kmod-nft-queue + xray-core

Thanks a lot for your help.
Best regards.

**Comment by marcoavesani** [comment]
You just need to add those lines in the modules.txt file. If you don't want to run the script via github actions you can just clone the repo and run the .sh file.

**Comment by MistFenix** [comment]
I understand, but could you please show me an example of how to add those correctly?

I really don't know, because beginning in this way, thanks bro

**Comment by MistFenix** [comment]
This is a very good project, If I learn how to work with this project, I can create it for my other router also. So, could you please teach me how to create correctly, I can pay for it 🙏

**Comment by MistFenix** [comment]
* check_data_file_clashes: Package dnsmasq wants to install file /home/clowwindy/Desktop/openwrt_image_build_rm2100-master/openwrt-imagebuilder-23.05.0-ramips-mt7621.Linux-x86_64/build_dir/target-mipsel_24kc_musl/root-ramips/etc/hotplug.d/ntp/25-dnsmasqsec
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /home/clowwindy/Desktop/openwrt_image_build_rm2100-master/openwrt-imagebuilder-23.05.0-ramips-mt7621.Linux-x86_64/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/dnsmasq
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /home/clowwindy/Desktop/openwrt_image_build_rm2100-master/openwrt-imagebuilder-23.05.0-ramips-mt7621.Linux-x86_64/build_dir/target-mipsel_24kc_musl/root-ramips/etc/uci-defaults/50-dnsmasq-migrate-ipset.sh
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /home/clowwindy/Desktop/openwrt_image_build_rm2100-master/openwrt-imagebuilder-23.05.0-ramips-mt7621.Linux-x86_64/build_dir/target-mipsel_24kc_musl/root-ramips/etc/uci-defaults/50-dnsmasq-migrate-resolv-conf-auto.sh
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /home/clowwindy/Desktop/openwrt_image_build_rm2100-master/openwrt-imagebuilder-23.05.0-ramips-mt7621.Linux-x86_64/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/dnsmasq/dhcp-script.sh
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /home/clowwindy/Desktop/openwrt_image_build_rm2100-master/openwrt-imagebuilder-23.05.0-ramips-mt7621.Linux-x86_64/build_dir/target-mipsel_24kc_musl/root-ramips/usr/sbin/dnsmasq
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /home/clowwindy/Desktop/openwrt_image_build_rm2100-master/openwrt-imagebuilder-23.05.0-ramips-mt7621.Linux-x86_64/build_dir/target-mipsel_24kc_musl/root-ramips/usr/share/acl.d/dnsmasq_acl.json
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /home/clowwindy/Desktop/openwrt_image_build_rm2100-master/openwrt-imagebuilder-23.05.0-ramips-mt7621.Linux-x86_64/build_dir/target-mipsel_24kc_musl/root-ramips/usr/share/dnsmasq/dhcpbogushostname.conf
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq wants to install file /home/clowwindy/Desktop/openwrt_image_build_rm2100-master/openwrt-imagebuilder-23.05.0-ramips-mt7621.Linux-x86_64/build_dir/target-mipsel_24kc_musl/root-ramips/usr/share/dnsmasq/rfc6761.conf
        But that file is already provided by package  * dnsmasq-full
 * opkg_install_cmd: Cannot install package dnsmasq.
make[2]: *** [Makefile:189: package_install] Error 255
make[1]: *** [Makefile:144: _call_image] Error 2
make: *** [Makefile:262: image] Error 2


How to solve these errors?

**Comment by marcoavesani** [comment]
The error is explained here:
`Package dnsmasq wants to install file /home/clowwindy/Desktop/openwrt_image_build_rm2100-master/openwrt-imagebuilder-23.05.0-ramips-mt7621.Linux-x86_64/build_dir/target-mipsel_24kc_musl/root-ramips/etc/hotplug.d/ntp/25-dnsmasqsec
But that file is already provided by package * dnsmasq-full`

During the make the script is trying to install "dnsmasq", however it conflicts with "dnsmasq-full" which has already flagged for installation. You need to check your modules.txt file if both "dnsmasq" and "dnsmasq-full" are present.
If this is not the case could be that "dnsmasq" is ethier installed by default or a dependency of another package.
In this case you have to add at the end of the modules.txt the command "-dnsmasq" wich explicitly avoids the installation of dnsmasq.

**Comment by marcoavesani** [comment]
Well, since this is not really an issue an a week passed I'm closing it
